version: "3.0"

services:
  grafana:
    image: grafana/grafana:11.2.0-ubuntu
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - "{{ grafana_deploy_dir }}/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml"
      - "{{ grafana_dashboards_dir }}:/var/lib/grafana/dashboards"
      - "{{ grafana_datasources_dir }}:/etc/grafana/provisioning/datasources"